import Foundation

/// Entry point for the MosaicKit core test suite. Run with `swift run mosaic-checks`.
@main
struct Checks {
    static func main() async {
        let r = CheckRunner()
        print("Running MosaicKit core checks…")

        runProviderChecks(r)
        runParserChecks(r)
        runDiffChecks(r)
        runAggregatorChecks(r)
        runRequestBuilderChecks(r)
        runKeychainChecks(r)
        runSearchChecks(r)
        runTagsChecks(r)
        runPinningChecks(r)
        runMarkdownChecks(r)
        runExportChecks(r)
        await runClientChecks(r)
        await runTranscriptionChecks(r)
        await RetrievalFoundationChecks.run(r)
        await RetrievalWeek2Checks.run(r)
        await RetrievalWeek3Checks.run(r)
        await RetrievalWeek5Checks.run(r)
        await RetrievalWeek6Checks.run(r)
        await EmbeddingProviderChecks.run(r)
        EmbeddingProviderChecks.runCloud(r)
        EmbeddingRouterChecks.run(r)
        EmbeddingRouterChecks.runCloudUpgradeHint(r)
        ProductionConfigChecks.run(r)
        DerivedConsistencyChecks.run(r)
        CloudSyncChecks.run(r)
        NotesUIChecks.run(r)
        ScenarioDatasetChecks.run(r)
        await ScenarioBaselineEvaluation.run(r)
        await QuerySegmentationSweep.run(r)
        await DerivedConsistencyChecks.runRetrieval(r)
        KeywordLatencyBreakdown.run(r)
        await KeywordLatencyBreakdown.checkCacheIsBitIdentical(r)
        await RetrievalProviderBenchmark.run(r)
        await IndexingCostAtScale.run(r)
        FusionDefaultChecks.run(r)
        await FusionSweep.run(r)
        await CloudEmbeddingResilienceChecks.run(r)
        await AbstentionChecks.run(r)
        AbstentionChecks.checkNotWiredToProduction(r)
        await EvalChecks.run(r)
        await HumanLikeGoldenChecks.run(r)
        await SearchPresentationChecks.run(r)
        await runLiveChecks(r)

        r.finish()
    }
}
